Goals for excercise
1. Load data as dataframe > Data Questions CHECK
2. Perform Univariate Analysis
3. Explore Unexpected Values > Reconcile this
4. Explore Variables
5. Remove Unuseful data
6. Explore Correlations beetween variables

Changed jupyter settings to accomodate data rate:  jupyter notebook --NotebookApp.iopub_data_rate_limit=1.0e10
**Data Limit permanently changed until changed back**

Policy Level, County Level, Multiple types of limits per policy, tiv?, deductible, line, construction, point of granularity

Data: Correlation or Causation relationships

Definition:
Deductible:  is the amount paid out of pocket by the policy holder before an insurance provider will pay any expenses
TIV: Highest site limit value

Context: Insurance per site considering different limits in Florida. What was the total insured value of the site. Compared the TIV between 2011 and 2012. (Story/Reason for Analysis) Insurance company is tracking the total insured value of a site across years. It seems they are increasing the total insured values.

Questions: 
Per county are there different policy limits? > Combine with financial data to re-calculate limits

Data Goal:
Visualize Holistic change in insurance value per year and a zoomed in version per site for a company.

In [5]:
import pandas as pd
df = pd.read_csv("/Users/ashenparikh/Downloads/FL_insurance_sample.csv")

In [8]:
df.columns

Index(['policyID', 'statecode', 'county', 'eq_site_limit', 'hu_site_limit',
       'fl_site_limit', 'fr_site_limit', 'tiv_2011', 'tiv_2012',
       'eq_site_deductible', 'hu_site_deductible', 'fl_site_deductible',
       'fr_site_deductible', 'point_latitude', 'point_longitude', 'line',
       'construction', 'point_granularity'],
      dtype='object')

In [9]:
df.head()

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1

In [10]:
df.shape

(36634, 18)

In [12]:
df.nunique(axis=0)

policyID              36634
statecode                 1
county                   67
eq_site_limit          5961
hu_site_limit         24531
fl_site_limit          4581
fr_site_limit          7536
tiv_2011              24804
tiv_2012              35295
eq_site_deductible      155
hu_site_deductible     2153
fl_site_deductible       43
fr_site_deductible        6
point_latitude        17900
point_longitude       17731
line                      2
construction              5
point_granularity         5
dtype: int64

In [13]:
df.describe().apply(lambda s: s.apply(lambda x: format(x, 'f')))

,policyID,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,point_granularity
count,36634.000000,36634.000000,36634.000000,36634.000000,36634.000000,36634.000000,36634.000000,36634.000000,36634.000000,36634.000000,36634.000000,36634.000000,36634.000000,36634.000000
mean,548661.937189,731478.006846,2074347.928476,664600.937028,991172.355861,2172875.000323,2571004.097342,778.790804,7037.984547,192.453210,26.483594,28.087477,-81.903565,1.640907
std,259912.926494,17523003.588415,19641497.135377,17461144.429799,17671776.714882,20150151.203414,20367766.569178,47879.794521,95825.926683,8037.713716,4702.740932,1.647734,1.809066,1.070561
min,100074.000000,0.000000,0.000000,0.000000,0.000000,90.000000,73.370000,0.000000,0.000000,0.000000,0.000000,24.547514,-87.447290,1.000000
25%,323647.750000,0.000000,42481.060000,0.000000,0.000000,45624.150000,54013.512500,0.000000,0.000000,0.000000,0.000000,26.471996,-82.439331,1.000000
50%,548525.000000,0.000000,192691.085000,0.000000,0.000000,202105.065000,241630.985000,0.000000,0.000000,0.000000,0.000000,28.057077,-81.585700,1.000000
75%,774252.000000,0.000000,916338.060000,0.000000,57410.100000,946582.132500,1128871.182500,0.000000,0.000000,0.000000,0.000000,29.623005,-80.372910,3.000000
max,999971.000000,2160000000.000000,2160000000.000000,2160000000.000000,2160000000.000000,2160000000.000000,1701000000.000000,6273765.000000,7380000.000000,450000.000000,900000.000000,30.989820,-80.033257,7.000000